### PR TITLE
Game logic

### PR DESCRIPTION
**Pull request by m-anwar97**
Made the game logic in two additional files board.rb and player.rb

### CODE REVIEW

**Review by Srjnnnn — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle: :stop_sign: 
Hello team!
I'd like to review your code but it throws an error when I run your main. I am giving the error below. Besides, in your pull request, the rubocop throws errors which you need to fix! :100: 

Here is the error;
Traceback (most recent call last):
        1: from bin/main:2:in `<main>'
bin/main:2:in `require_relative': /home/srjnnnn/Documents/Yazılım/Microverse/Reviews/Tic-Tac-Toe/lib/board.rb:77: syntax error, unexpected `end', expecting end-of-input (SyntaxError)

You have one additional end so please fix this. When you are finished with your code, kindly submit for a re-review.
If you have a question about the review, feel free to reach me via Slack. :+1: 
Eyüp Sercan UYGUR

**Review by Georjane — CHANGES_REQUESTED** [review]
## **Status: Changes Required**:x::warning:
Hello @coldatlas  :raised_hands:

- I see you have done a great job so far:clap:, but I am unable to play the game 🔢  because it throws an error message after the input the player's names and I type in either 'X' or 'O' as a player choice. I get the following error message:

error message

- Also, your linters are not passing :x:  You have a couple of rubocop errors, some of which can be fixed using `rubocop -a`, and the others, you need to adjust your code.

- No puts/print and get.chomp outside main.rb file. Remove the puts in your board.rb file and also inline comments.

Please address the required changes and submit them for another code review.
Feel free to reach out to me on Slack if you have ant questions, **Witah Georjane** 🤝 

Good luck and Happy Coding 💻

**Review by Srjnnnn — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle: :stop_sign: 
Hello team!
Good job till here! It's getting better. However, there are things you need to work on before moving on. :cat: 

- [ ] Your project has linter errors. Please fix them.

- [x] Right now a player can choose an occupied place and it's changing the symbol with the last input. Kindly fix this issue.

- [x] Right now, with an invalid input the game asks for an integer input, and then it stops. It shouldn't stop and it should keep asking a valid input. Please fix this issue.

- [ ] On your main file, you've disabled some rubocop checks. I recommend not to disable them.

Please fix those issues and submit for a re-review. :100: 
If you have a question about the review, feel free to reach me via Slack.
Eyüp Sercan UYGUR

**Review by tirthajyoti-ghosh — APPROVED** [review]
# Approved ✅

## You have done an incredible job making this project 👏🧨💪! Just perfect 💯! 

### You have met all the requirements of the project. Go ahead and merge it! Onto the next project 🚀 !

Happy coding 👨‍💻 

<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

**Pull request merged**
